config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, :controllers => { :registrations => 'registrations' }, :path => '', :path_names => { :sign_in => '', :sign_up => 'new', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }

  # as :user do
  #   get 'users/edit' => 'devise/registrations#edit', :as=>'edit_user_registration'
  #   put 'users/:id' => 'devise/registrations#update', :as=>'user_registration'
  # end
  
  resources :tickets, :except => [:show] do
    post :index, on: :collection
    post :add_comments, on: :collection
    post :check_comment, on: :collection
    post :change_rows, on: :collection
    post :quickadd, on: :collection
    # post :filter, on: :collection
    # post :setrows, on: :collection
  end
  
  get "/devices/security" => "devices#security"
  get "/devices/password" => "devices#password"

  resources :devices do
    # post :filter, on: :collection
    # post :setrows, on: :collection
    # post :saction, on: :collection
    post :tickets, on: :collection
    post :usage, on: :collection
    post :security, on: :collection
    post :password, on: :collection
    post :cancel_request, on: :collection

  end

  get "/customers" => "customers#index"

  resources :customers, :except=>[:new, :show, :delete, :edit] do
    post :modify, on: :collection
  end
  
  get "/dashboard" => "dashboard#index"
  # get "/new" => "sessions#new"
  # root :to => "users#sign_in"

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]  
  match "/500" => "errors#internal_error", via: [ :get, :post, :patch, :delete ]  
  match '/422' => 'errors#unprocessable_entity', via: [ :get, :post, :patch, :delete ]  

end

app/models/device.rb
class Device < ActiveRecord::Base
  self.table_name = "Devices"

  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000)
    end while Model.where(id: self.id).exists?
  end

  def self.search(filter_item, username)
  
    if !filter_item.blank? && !filter_item[:name].nil?
      tmp = filter_item

      devices = Device.where("name LIKE ? AND location LIKE ? AND device_type LIKE ? AND public_ip LIKE ? AND private_ip LIKE ?", "%#{tmp[:name]}%", "%#{tmp[:location]}%", "%#{tmp[:device_type]}%", "%#{tmp[:public_ip]}%", "%#{tmp[:private_ip]}%")
    else
      devices = Device.where(:owner=>username)
    end
  
    return devices
  end

  def self.saction(params)

    if !params.blank? && !params[:device_name].nil?
      tmp = Device.find_by_name(params[:device_name])

      dnote = Dnote.new(:device_id=>tmp.id,:device_name=>tmp.name,:device_status=>tmp.general_status,:is_checked=>false,:request_order=>params[:request])
      dnote.save

      tmp.detail = "updated"
      tmp.save
    end

  end

  def self.device_sortable(column, direction)
    case column
    when "Name"
      col = "name "
    when "Type"
      col = "device_type "
    when "Location"
      col = "location "
    when "Public IP"
      col = "public_ip "
    when "Private IP"
      col = "private_ip "
    when "Start Time"
      col = "created_at "
    else
      col = " "
    end

    return col + direction
  end

  def self.to_thdindex(sort_item)
    case sort_item
    when "Name"
      col = 0
    when "Type"
      col = 1
    when "Location"
      col = 2
    when "Public IP"
      col = 3
    when "Private IP"
      col = 4
    when "Start Time"
      col = 5
    else
      col = 6
    end

    return col
  end

end

# if Device.connection.nil?
#   Device.establish_connection "user_panel_#{Rails.env}"
# end

app/controllers/devices_controller.rb
require 'will_paginate/array'

class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    # @devices = Device.all
    @devices = Device.where(:owner=>current_user.username)
    
    # sort
    @thd = []

    if !params[:sort_item].nil?
      did = Device.to_thdindex(params[:sort_item])

      if params[:direction] != ""
        if params[:direction] == "desc"
          @thd[did] = "_d"
        else
          @thd[did] = "_a"
        end
      end
    end
    
    if !params[:sort_item].nil?
      str_order = Device.device_sortable(params[:sort_item], params[:direction])
    end

    # filter
    if !params[:name].nil?
      @filter_params = params
    end

    # saction
    if !params[:device_name].nil?
      Device.saction(params)
    end

    # show filtered and sorted
    if str_order.nil?
      @devices = Device.search(@filter_params, current_user.username).order(:updated_at=>:desc)
    else
      @devices = Device.search(@filter_params, current_user.username).order(str_order).order(:updated_at=>:desc)
    end

    # paginate
    if params["device_rows"].nil? || params["device_rows"].blank?
      @rows = 5
    else 
      @rows = params["device_rows"]
    end

    if params[:page].nil?
      @page_number = 1
    else
      @page_number = params[:page]
    end
    
    @devices = @devices.paginate(:page => params[:page], :per_page => @rows.to_i)

    tmp = Dnote.where(:is_checked=>"0")
    @dnote_count = tmp.count

    if @dnote_count > 0
      @dnote_content = tmp.last.request_order
    end

  end

  # def filter
  #   redirect_to devices_url, flash:{filter_str:params}
  # end

  # def setrows
  #   redirect_to devices_url, flash:{rows:params["device_rows"]}
  # end

  # def saction
  #   tmp = params
  #   redirect_to devices_url, flash:{saction:tmp}
  # end

  # def tickets
  #   tmp = params[:device_id]
  #   @tickets = Ticket.where(:device_id=>tmp).order(:updated_at=>:desc).paginate(:page=>params[:page], :per_page=>5)      
  #   @comments = Comment.all

  #   # Paginate
  #   if params["ticket_rows"].nil?
  #     @rows = 5
  #   else 
  #     @rows = params["ticket_rows"]
  #   end
  #   # setrows
  #   if params[:page].nil?
  #     @page_number = 1
  #   else
  #     @page_number = params[:page]
  #   end

  #   # show page number
  #   if params[:page].nil?
  #     @page_number = 1
  #   else
  #     @page_number = params[:page]
  #   end

  #   @ticket_count = @tickets.count
  # end

  def security
    @dname = params[:device_name]
    
    # Paginate
    if params[:security_rows].nil?
      @rows = 5
    else 
      @rows = params[:security_rows]
    end

    # delete a request from security table
    if !params[:dnote_id].nil?
      Dnote.find_by_id(params[:dnote_id]).delete
    end

    # show page
    if params[:page].nil?
      @page_number = 1
    else
      @page_number = params[:page]
    end

    @filter_word = params[:filter_word]
    @dnotes = Dnote.search(params[:filter_word], @dname).order(:updated_at=>:desc)
    number_entries = @dnotes.count
    @dnotes = @dnotes.paginate(:page=>params[:page], :per_page=>@rows, :total_entries => number_entries> 25 ? 25 : number_entries )
    # fresh_when @dnotes
  end

  def cancel_request
    if !params[:id].nil?
      dn = Dnote.find_by_id(params[:id])

      if !dn.nil?
        dn.delete
      end
    end

    render json:nil, status: :ok
  end

  def usage
    @dname = params[:device_name]
    @ulogs = Dnote.where(:device_name=>@dname).order(:updated_at=>:desc)
  end

  def password
    # set page rows
    if params[:password_rows].nil? || params[:password_rows].blank?
      @rows = 5
    else 
      @rows = params[:password_rows]
    end
    # show page number
    if params[:page].nil?
      @page_number = 1
    else
      @page_number = params[:page]
    end

    if params[:button2] == 'modify'
      du = DeviceUser.find_by_device_name(params[:device_name])

      if !du.nil? || !du.blank?
        du.update(:username=>params[:username], :password=>params[:password], :device_name=>params[:device_name])
      end
    end

    if params[:button2] == 'remove'
      du = DeviceUser.find_by_device_name(params[:device_name])
      if !du.blank?
        du.delete
      end

      # de = Device.where(:name=>params[:device_name])
      de = Device.find_by_name(params[:device_name])

      if !de.blank?
        de.delete
      end
    end
    
    @dname = params[:device_name]
    # @devices = Device.where(:owner=>current_user.username).order(:updated_at=>:desc).paginate(:page=>params[:page], :per_page=>@rows)
    @devices = Device.where(:name => @dname).order(:updated_at=>:desc).paginate(:page=>params[:page], :per_page=>@rows)
    @count = DeviceUser.all.count
    
  end

  def modify_duser
    redirect_to password_devices_path
    # redirect_to devices_url
  end
  # GET /devices/1
  # GET /devices/1.json
  def show
    # saction
    if !params[:device_id].nil?
      Device.saction(params)
    end

    tmp = Dnote.where(:is_checked=>"0")
    @dnote_count = tmp.count

    if @dnote_count > 0
      @dnote_content = tmp.last.request_order
    end
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create

    @device = Device.new(device_params)
    @device.id = 100000 + rand(999999-100000)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end

    # UserMailer.cdevice_email(@device, current_user).deliver
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :device_type, :location, :public_ip, :private_ip)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_security.html.erb
<div class="content-div" style="margin-bottom:9%">
  <h1>
    Usage Logs <!-- <span id="span_security">- <%= @dname %></span> -->
    <% if hp_device(current_user.email) %>
      <%#= link_to 'New Device', new_device_path, :class=>'btn btn-primary btn-device' %>
    <% end %>
  </h1>
  <div style="text-align:right;">
    <%= link_to 'View All Devices', devices_path, :class=>'btn btn-primary btn-device', :style=>'right:0px;margin-top:-80px;' %>    
  </div>

  <!-- <div style="padding: 10px 0;min-width:930px;"> -->
  <div style="padding: 10px 0;">
    <div class="col-lg-6" style="display:inline-block;">
      <div class="col-lg-4" style="margin-top:9px;">
        <% if @dnotes.nil? || @dnotes.blank? %>
          Viewing 0 to 0 of 0
        <% else %>
          Viewing 
          <% if @page_number == 1 %> 
            <%= 1 %>
          <% else %>
            <%= 1 + (@page_number.to_i - 1) * @rows.to_i %>
          <% end %>
          to 
          <span id="span_dncount1">
            <% if @rows.to_i*@page_number.to_i > @dnotes.count %>
              <%= @dnotes.count %> 
            <% else %>
              <%= @rows.to_i*@page_number.to_i %> 
            <% end %>
          </span>
          of <span id="span_dncount2"><%= @dnotes.count %></span>
        <% end %>
        &nbsp;&nbsp;
      </div>
      <div class="col-lg-8" style="position:relative;top:-11px;">
        Displaying&nbsp;
        <%#= form_tag('/devices/security', :id=>'form_security_rows', :style => 'display:inline-block;') do -%>
        <%= simple_form_for :security_rows, :method=>'get', :remote=>true, :html=>{:id=>'form_security_rows', :style=>'display:inline-block;'} do |f| %>
          <%= hidden_field_tag "device_name", nil, :value=>@dname %>
          <div class="dropdown dropdown-dark" style="width:70px;top:12px;">
            <select name="security_rows" class="dropdown-select small" id="select_security_rows">
              <% [5,10,20,50].each do |n| %>
                <% if @rows.to_i == n %>
                  <option value="<%=n%>" selected="selected"><%=n%></option>
                <% else %>
                  <option value="<%=n%>"><%= n%></option>
                <% end %>
              <% end %>
            </select>
          </div>
          <%#= hidden_field_tag "device_rows" %>&nbsp;
          <%#= select_tag "combo_device_rows", options_for_select([ "5", "10", "20", "50" ], @rows) %>per page
        <% end -%>
      </div>
    </div>

    <div class="col-lg-3" style="margin-top:3px;">
      <%= will_paginate @dnotes, :previous_label => '<', :next_label => '>' %>
    </div>

    <div class="col-lg-3" style="display:inline-block;text-align:right;float:right;">
      <!-- <i class="glyphicon glyphicon-refresh" id="btn_refresh_device" style="cursor:pointer"></i>
      &nbsp; -->
      <%= simple_form_for :filter, :method=>'get', :remote=>true, :html=>{:id=>'form_security_filter', :style=>'display:inline-block;'} do |f| %>
        <%= text_field_tag :filter_word, nil, :class=>'form-control', :style=>'display:inline-block;padding-right:90px;', :value=>@filter_word %>
        <%= hidden_field_tag "device_name", nil, :value=>@dname %>
        <%= button_tag(:class=>'btn btn-primary btn-reply2 btn-device', :id=>'btn_filter_devices', :style=>'margin-top:-54px;') do %>
          Filter&nbsp;&nbsp;<i class="glyphicon glyphicon-filter" style="font-size:14px;position:relative;top:3px;color:ine"></i>
        <% end %>
      <% end %>
    </div>    
  </div>


  <table class="listing" id="table_security" style="margin-top:20px;">
    <thead>
      <tr>
        <th></th>
        <th>Device Name</th>
        <th>Activity</th>
        <th>Request Order</th>
        <th>Status</th>
        <th>Worked Date</th>
        <th style="text-align:center;">Action</th>
        <!-- <th>Delete</th> -->
      </tr>
    </thead>

    <tbody>
      <% if @dnotes.blank? %>
        <tr>
          <td></td>
          <td colspan="7">No Logs</td>
        </tr>
      <% else %>
        <% @dnotes.each do |device| %>
          <tr id="tr_dnote_<%=device.id%>">
            <td style="color:transparent;"><%=device.id%></td>
            <%
            if pro_action(device.is_checked) == "Pending" 
              bd = true
            else 
              bd = false
            end 
           %>
            <td class="clickable">
              <%#= raw(get_colorspan(bd, '<i class="fa fa-fw fa-cog" style="font-size:16px;"></i>')) %>
              <%#= raw(get_colorspan(bd,processblank(device.device_name))) %>
              <%= raw(processblank(device.device_name)) %>
            </td>
            <td class="clickable">
              <% if device.device_status == 'Deactive' %>
                <%#= raw(get_colorspan(bd, '<i class="fa fa-fw fa-times-circle" style="font-size:16px;"></i>')) %>
                <i class="fa fa-fw fa-times-circle" style="font-size:16px;"></i>
              <% else %>
                <%#= raw(get_colorspan(bd, '<i class="fa fa-fw fa-check-circle" style="font-size:16px;"></i>')) %>
                <i class="fa fa-fw fa-check-circle" style="font-size:16px;"></i>
              <% end %>
              <%#= raw(get_colorspan(bd,processblank(device.device_status))) %>
              <%= processblank(device.device_status) %>
            </td>
            <td class="clickable">
              <% if processblank(pro_action(device.request_order)) != '---' %>
                <%#= raw(get_colorspan(bd, '<i class="fa fa-fw fa-tag" style="font-size:16px;"></i>')) %>
                <i class="fa fa-fw fa-tag" style="font-size:16px;"></i>
              <% end %>
              <%#= raw(get_colorspan(bd,processblank(device.request_order))) %>
              <%= raw(processblank(device.request_order)) %>
            </td>
            <td class="clickable">
              <% if bd %>
                <%= raw(get_colorspan(bd, '<i class="fa fa-fw fa-spinner" style="font-size:16px;"></i>')) %>
              <% else %>
                <i class="fa fa-fw fa-check-circle" style="font-size:16px;"></i>
              <% end %> 
              <%= raw(get_colorspan(bd,processblank(pro_action(device.is_checked)))) %>
            </td>
            <td class="clickable">
              <%= raw(get_colorspan(bd, '<i class="fa fa-fw fa-clock-o" style="font-size:16px;"></i>')) %>
              <%= raw(get_colorspan(bd,processblank(time_ago_in_words(device.updated_at)))) %>&nbsp;<%= raw(get_colorspan(bd,"ago"))%>
            </td>
            <td class="clickable devicelog_td_5" style="text-align:center;">
              <% if pro_action(device.is_checked) == "Pending" %>
                <%= simple_form_for :dnote_id, :method=>'get', :remote=>true, :html=>{:id=>'form_delete_slog'} do |f| %>
                  <%= hidden_field_tag "dnote_id", nil, :value=>device.id.to_s %>
                  <%= hidden_field_tag "device_name", nil, :value=>device.device_name %>
                  <%= button_tag(type:"submit", :style=>'background-color:transparent;font-weight:100;border:none;') do %>
                    <i class="fa fa-fw fa-times-circle" style="font-size:16px;color:white"></i>&nbsp;Cancel
                  <% end %>
                <% end %>
              <% else %>
                ---
              <% end %>
            </td>
          </tr>            
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

<script>
  var headertext = [],
  headers = document.querySelectorAll('#table_security th'),
  tablerows = document.querySelectorAll('#table_security th'),
  table_body = document.querySelector('#table_security tbody');

  for (var i = 0; i < headers.length; i++) {
    var current = headers[i];

    headertext.push(current.textContent.replace(/\r?\n|\r/,""));
  }

  for (var i = 0, row; row = table_body.rows[i]; i++) { 
    for(var j = 2, col; col = row.cells[j]; j++) {
      if ( headertext[j] )  {
        col.setAttribute('data-th', headertext[j]);
      }

      if ( j != 6 ) {
        col.setAttribute('style', 'text-align:left;');
      }
    }

    if ( i%2 == 1 ) {
      col = row.cells[0];
    }
  }

  function update_span(sid) {
    var nc = $.trim($(sid).text());
    nc = nc - 1;
    $(sid).text(nc);
    $(sid).val(nc);
  }

  $(function() {
    $('.pagination a').attr('data-remote', 'true');
    // $('#select_security_rows').attr('data-remote', 'true');
  });
</script>

app/views/devices/edit.html.erb
<h1 style="color:white;text-align:center">Editing Device</h1>

<%= render 'form' %>

<%#= link_to 'Show', @device %> |
<%#= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<div class="container">
  <div id="show_notice">
    <%= render 'show_notice' %>
  </div>

  <div class="content-div" style="overflow:hidden;margin-bottom:9%">
    <h1 style="display:inline-block">Device Details</h1>
    <div style="text-align:right;">
      <%= link_to 'View All Devices', devices_path, :class=>'btn btn-primary btn-device', :style=>'right:0px;margin-top:-80px;' %>    
    </div>
    <div style="border:8px solid rgba(99, 154, 195, 0.36);overflow:hidden;margin:15px 0;">

      <div class="col-lg-2" style="text-align:left;padding-top:15px;">
        <%= image_tag('server1.png', size: "120") %>
      </div>
      <div class="col-lg-7">
        <h3><i class="fa fa-fw fa-cog"></i>&nbsp;<%= @device.name %></h3><br/>
        <i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;Public IP:&nbsp;&nbsp;<%= @device.public_ip %><br/><br/>
        <i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;Private IP:&nbsp;&nbsp;<%= @device.private_ip %><br/><br/>
      </div>

      <div class="col-lg-3" style="text-align:right">
        <div class="dropdown dropdown-dark" style="width:150px;top:12px;" id="select_device_action">
          <select name="two" class="dropdown-select small">
            <option value="">Action</option>
            <option value="Reboot">Reboot</option>
            <option value="Power On / Off">Power On / Off</option>
            <option value="Rescue">Rescue</option>
            <option value="OS Reload">OS Reload</option>
            <option value="Load From Image">Load From Image</option>
            <!-- <option value="Create Image Template">Create Image Template</option> -->
            <option value="Create Flex Image">Create Flex Image</option>
            <!-- <option value="Migrate to Local Disk">Migrate to Local Disk</option> -->
            <option value="Rename Instance">Rename Instance</option>
            <option value="Port Control">Port Control</option>
            <option value="View Audit Logs">View Audit Logs</option>
            <option value="KVM Console">KVM Console</option>
            <option value="Cancel Device">Cancel Device</option>
          </select>
        </div>
      </div>
    </div>

    <%#= form_tag('/devices/saction', method: :post, :id=>'form_send_actions', :style=>'display:none') do -%>
    <%= simple_form_for @device, :method=>'get', :remote=>true, :html=>{:id=>'form_send_actions'} do |f| %>
      <%= hidden_field_tag "device_id", nil, :value=>@device.id %>
      <%= hidden_field_tag "device_name", nil, :value=>@device.name %>
      <%= hidden_field_tag "device_status", nil, :value=>@device.general_status %>
      <%= hidden_field_tag "is_checked", nil, :value=>false %>
      <%= hidden_field_tag "request_order" %>
    <% end -%>

    <div style="border:8px solid rgba(99, 154, 195, 0.36);overflow:hidden;margin:15px 0;">
      <div class="col-lg-6" >
        <h3><i class="fa fa-fw fa-comments"></i>&nbsp;Note</h3><br/>
        <%= @device.device_note %> <br/><br/>
        <%=%>
      </div>
      <div class="col-lg-6" >
        <!-- <div class="col-lg-12"> -->
          <h3><i class="fa fa-fw fa-folder"></i>&nbsp;Addons</h3><br/>
        <!-- </div> -->

        <!-- <div class="col-lg-12"> -->
          <%= @device.addons %><br/><br/>
        <!-- </div> -->
      </div>
    </div>

    <div style="border:8px solid rgba(99, 154, 195, 0.36);overflow:hidden;margin:15px 0;">
      <div class="col-lg-12">
        <h3><i class="fa fa-fw fa-paperclip"></i>&nbsp;Gerneral</h3><br/>
      </div>

      <div class="col-lg-6">
        <i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;Status: <%= @device.general_status == "Active" ? raw('<i class="fa fa-fw fa-check-circle"></i>&nbsp;') + @device.general_status : raw('<i class="fa fa-fw fa-ban"></i>&nbsp;') + @device.general_status %><br/><br/>
        <i class="fa fa-fw fa-calendar"></i>&nbsp;Start Date: <%=@device.created_at%><br/><br/>
        <i class="fa fa-fw fa-refresh"></i>&nbsp;Reloaded: <%= @device.general_reloaded == "Reloaded" ? raw('<i class="fa fa-fw fa-check"></i>&nbsp;') + @device.general_reloaded : raw('<i class="fa fa-fw fa-ban"></i>&nbsp;') + @device.general_reloaded %><br/><br/>
        <%=%>
      </div>
      <div class="col-lg-6">
        <i class="fa fa-fw fa-globe"></i>&nbsp;Location: &nbsp;<%= raw(getflag_floc(@device.location)) + ' ' + @device.location %><br/><br/>
        <i class="fa fa-fw fa-bell"></i>&nbsp;Last Trans: Transfer Monitoring Robot<br/><br/>
        <%=%>
      </div>
    </div>

    <div style="border:8px solid rgba(99, 154, 195, 0.36);overflow:hidden;margin:15px 0;">
      <div class="col-lg-12">
        <h3><i class="fa fa-fw fa-linux"></i>&nbsp;System</h3><br/>
      </div>

      <div class="col-lg-6">
        <i class="fa fa-fw fa-windows"></i>&nbsp;OS: <%= @device.osname%><br/><br/>
        <i class="fa fa-fw fa-hdd-o"></i>&nbsp;RAM: <%= @device.osram %><br/><br/>
        <i class="fa fa-fw fa-apple"></i>&nbsp;Processor: <%= @device.osprocessor%><br/><br/>
        <%=%>
      </div>
      <div class="col-lg-6" style="text-align:right">
        <%= image_tag('os1.png', size: "273 87") %>
      </div>
    </div>

    <div style="border:8px solid rgba(99, 154, 195, 0.36);overflow:hidden;margin:15px 0;">
      <div class="col-lg-12">
        <h3><i class="fa fa-fw fa-cloud-upload"></i>&nbsp;Network</h3><br/>
      </div>

      <div class="col-lg-6">
        <div class="col-lg-6">
          <h4>Public: </h4>
        </div>
        <div class="col-lg-6" style="text-align:right">
          <%= link_to 'Order IPs', devices_path, :class=>'btn btn-primary btn-device' %>
          <br/>
          <br/>
        </div>
        <div class="col-lg-12">
          <h4>eth1</h4><br/>
          Status: ACTIVE<br/><br/>
          IP Address: 159.122.101.228<br/><br/>
          Default Gateway: 159.122.101.225<br/><br/>
          Subnet Mask: 255.255.255.240<br/><br/>
          Speed: 1000 Mbps<br/><br/>
          Max Speed: 1000 Mbps<br/><br/>
          VLAN: <u>fra02.bcr01a.1160</u><br/><br/>
          <%=%>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="col-lg-6">
          <h4>Private: </h4>
        </div>
        <div class="col-lg-6" style="text-align:right">
          <%= link_to 'Order IPs', devices_path, :class=>'btn btn-primary btn-device' %>
          <br/>
          <br/>
        </div>
        <div class="col-lg-12">
          <h4>eth0</h4><br/>
          Status: ACTIVE<br/><br/>
          IP Address: 159.122.101.228<br/><br/>
          Default Gateway: 159.122.101.225<br/><br/>
          Subnet Mask: 255.255.255.240<br/><br/>
          Speed: 1000 Mbps<br/><br/>
          Max Speed: 1000 Mbps<br/><br/>
          VLAN: <u>fra02.bcr01a.1160</u><br/><br/>
          <%=%>
        </div>
      </div>
    </div>

    <div style="border:8px solid rgba(99, 154, 195, 0.36);overflow:hidden;margin:15px 0;">
      <div class="col-lg-12">
        <h3><i class="fa fa-fw fa-terminal"></i>&nbsp;Software</h3><br/>
      </div>

      <div class="col-lg-6">
        CentOS6.0-64 Minimal for VSI<br/><br/>
        cPanel cPanel for CloudLayer w/ RVSkin w/ SoftaculousStable<br/><br/>
        Nimsoft Nimsoft Robot5.0<br/><br/>
        <%=%>
      </div>
      <div class="col-lg-6" style="text-align:right">
        <%= image_tag('soft1.png', size: "94x75") %>
      </div>
    </div>

  </div>
</div>
  <%#= link_to 'Edit', edit_device_path(@device), :class=>'btn btn-primary' %>
  <%#= link_to 'Back', devices_path, :class=>'btn btn-primary' %>

app/views/devices/show.js.erb
jQuery('#show_notice').html("<%= j(render 'show_notice') %>");