config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, :controllers => { :registrations => 'registrations' }, :path => '', :path_names => { :sign_in => '', :sign_up => 'new', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification' }

  # as :user do
  #   get 'users/edit' => 'devise/registrations#edit', :as=>'edit_user_registration'
  #   put 'users/:id' => 'devise/registrations#update', :as=>'user_registration'
  # end
  
  resources :tickets, :except => [:show] do
    post :index, on: :collection
    post :add_comments, on: :collection
    post :check_comment, on: :collection
    post :change_rows, on: :collection
    post :quickadd, on: :collection
    # post :filter, on: :collection
    # post :setrows, on: :collection
  end
  
  get "/devices/security" => "devices#security"
  get "/devices/password" => "devices#password"

  resources :devices do
    # post :filter, on: :collection
    # post :setrows, on: :collection
    # post :saction, on: :collection
    post :tickets, on: :collection
    post :usage, on: :collection
    post :security, on: :collection
    post :password, on: :collection
    post :cancel_request, on: :collection

  end

  get "/customers" => "customers#index"

  resources :customers, :except=>[:new, :show, :delete, :edit] do
    post :modify, on: :collection
  end
  
  get "/dashboard" => "dashboard#index"
  # get "/new" => "sessions#new"
  # root :to => "users#sign_in"

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]  
  match "/500" => "errors#internal_error", via: [ :get, :post, :patch, :delete ]  
  match '/422' => 'errors#unprocessable_entity', via: [ :get, :post, :patch, :delete ]  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  self.table_name = "Tickets"

  def self.quickadd(add_item)

    @ticket = Ticket.new
    @ticket.id = 100000 + rand(999999-100000)

    @ticket.ticket_group = add_item["group"]
    @ticket.subject = add_item["subject"]
    @ticket.last_replied = add_item["last_replied"]
    @ticket.updated = add_item["updated"]
    @ticket.device = add_item["device"]
    @ticket.owner = add_item["owner"]
    # @ticket.user_id = add_item["user_id"]
    @ticket.is_read = add_item["is_read"]

    if @ticket.save
      # UserMailer.created_email(@ticket, current_user).deliver
      # format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
      # format.json { render :show, status: :created, location: @ticket }
      return true
    else
      return false
    end
  end

  def self.add_comments(comment_params)
    if !comment_params.blank?
      if comment_params[:commit] == "Reply"
        comment = Comment.new
        
        comment.comment = comment_params[:content]
        comment.ticket_id = comment_params[:ticket_id]
        comment.ticket_owner = comment_params[:ticket_owner]
        comment.save

        current_ticket = Ticket.find_by_id(comment_params[:ticket_id])
        current_ticket.is_read = comment_params[:is_read]
        current_ticket.save
      end
    end
  end

  def self.search(filter_item)
    
    if !filter_item.blank? && !filter_item[:group].nil?
      tmp = filter_item
      
      tickets = Ticket.where("subject LIKE ? AND ticket_group LIKE ? AND owner LIKE ? AND device LIKE ? AND last_replied LIKE ? AND updated_at LIKE ?", "%#{tmp[:subject]}%", "%#{tmp[:group]}%", "%#{tmp[:onwer]}%", "%#{tmp[:device]}%", "%#{tmp[:last_replied]}%", "%#{tmp[:updated]}%")
    else
      tickets = Ticket.all
    end

    return tickets
  end

  def self.ticket_sortable(column, direction)
    case column
    when "Ticket #"
      col = "id "
    when "Group"
      col = "ticket_group "
    when "Subject"
      col = "subject "
    when "Owner"
      col = "owner "
    when "Last replied"
      col = "last_replied "
    when "Device"
      col = "device "
    when "Updated"
      col = "updated_at "
    else
      col = " "
    end

    return col + direction
  end

  def self.to_thdindex(sort_item)
    case sort_item
    when "Ticket #"
      col = 0
    when "Group"
      col = 1
    when "Subject"
      col = 2
    when "Owner"
      col = 3
    when "Last replied"
      col = 4
    when "Device"
      col = 5
    when "Updated"
      col = 6
    else
      col = 7
    end

    return col
  end

end

# if Ticket.connection.nil?
#   Ticket.establish_connection "user_panel_#{Rails.env}"
# end

app/controllers/tickets_controller.rb
require 'will_paginate/array'

class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    # confirm permission
    tmp = User.find_by_email(current_user.email)
    if !tmp.nil?
      if tmp.is_rticket || tmp.is_sticket || tmp.is_dticket || tmp.is_wticket
        bis = true
      else
        bis = false
      end
    else
      bis = false
    end
    
    # quick add
    if !params[:quickadd].blank?
      Ticket.quickadd(params[:quickadd])
    end
    
    # filter
    if !params[:group].nil?
      @filter_params = params
    end
    
    # sort
    @thd = []

    if !params[:sort_item].nil?
      did = Ticket.to_thdindex(params[:sort_item])

      if params[:direction] != ""
        if params[:direction] == "desc"
          @thd[did] = "_d"
        else
          @thd[did] = "_a"
        end
      end
    end

    if !params[:sort_item].nil?
      str_order = Ticket.ticket_sortable(params[:sort_item], params[:direction])
    end
    
    if str_order.nil?
      @tickets = Ticket.search(@filter_params).order(:is_read=>:desc).order(:updated_at=>:desc)
    else
      @tickets = Ticket.search(@filter_params).order(str_order).order(:is_read=>:desc).order(:updated_at=>:desc)
    end
    fresh_when @tickets

    # leave comment
    @comments = Comment.order(:updated_at=>:desc)
    # Paginate
    if params["ticket_rows"].nil?
      @rows = 5
    else 
      @rows = params["ticket_rows"]
    end

    # show page number
    if params[:page].nil?
      @page_number = 1
    else
      @page_number = params[:page]
    end

    # show info on notification bar
    if !@tickets.blank? || !@tickets.nil?
      @tickets = @tickets.paginate(:page => params[:page], :per_page => @rows.to_i)
    end

    tmp = Ticket.where(:owner=>current_user.username)
    # fresh_when tmp
    @open_tickets = tmp.count

    tmp = Ticket.where(:owner=>current_user.username, :is_read=>true)
    # fresh_when tmp
    # tmp = Ticket.where(:is_read=>true)

    # add comment
    if !params[:content].nil?
      Ticket.add_comments(params)
    end
    
    @note_count = tmp.count
    @ticket_count = @tickets.count
  end

  # def setrows
  #   redirect_to tickets_url, flash:{rows:params["ticket_rows"]}
  # end

  # def filter
  #   redirect_to tickets_url, flash:{filter_str:params}
  # end
  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  def quickadd
    @ticket = Ticket.new
    @ticket.id = 100000 + rand(999999-100000)

    @ticket.ticket_group = params["/tickets/quickadd"]["group"]
    @ticket.subject = params["/tickets/quickadd"]["subject"]
    @ticket.last_replied = params["/tickets/quickadd"]["owner"]
    @ticket.updated = params["/tickets/quickadd"]["updated"]
    @ticket.device = params["/tickets/quickadd"]["device"]
    @ticket.owner = params["/tickets/quickadd"]["last_replied"]
    # @ticket.user_id = params["/tickets/quickadd"]["user_id"]
    @ticket.is_read = params["/tickets/quickadd"]["is_read"]

    if @ticket.save
      UserMailer.created_email(@ticket, current_user).deliver
      # format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
      # format.json { render :show, status: :created, location: @ticket }
    end

    redirect_to tickets_url
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @user_name = current_user.id

    @emails = current_user.username
    # users = User.all
    # users.each do |u| 
    #   # @emails.push(u.email.split("@").first)
    # end

    # @devices = Device.all
    @devices = Device.where(:owner=>current_user.username)
  end

  def add_comments
    # add comment
    @tickets = Ticket.all

    if params[:commit] == "Reply"
      @comment = Comment.new
      # binding.pry
      # @comment.user_id = params[:user_id]
      # @comment.user_email = params[:user_email]
      # @comment.ticket_id = params[:ticket_id]
      # @comment.ticket_name = params[:ticket_name]
      # @comment.content = params[:content]
      @comment.comment = params[:content]
      @comment.ticket_id = params[:ticket_id]
      @comment.ticket_owner = params[:ticket_owner]

      current_ticket = @tickets.find_by_id(params[:ticket_id])
      current_ticket.is_read = params[:is_read]
      current_ticket.save

      if @comment.save
        UserMailer.comment_email(@comment).deliver
        # format.html { redirect_to @ticket, notice: 'Comment was successfully created.' }
        # format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end

    redirect_to tickets_url
  end

  def check_comment 
    m_ticket = Ticket.find_by_id(params[:ticket_id]);
    m_ticket.is_read = false
    m_ticket.save
    render nothing: true
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.id = 100000 + rand(999999-100000)

    respond_to do |format|
      if @ticket.save
        UserMailer.created_email(@ticket, current_user).deliver
        format.html { redirect_to tickets_url, notice: 'Ticket was successfully created.' }
        # format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        # format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:ticket_group, :subject, :owner, :last_replied, :device, :updated, :user_id, :is_read, :detail)
    end

end

app/helpers/tickets_helper.rb
module TicketsHelper
  
end

app/views/tickets/_add_comment.html.erb
<br/><% up_ind = 0 %>
<% @comments.each do |comment| %>
  <% if comment.ticket_id == ticket.id.to_s %>

    <div class="col-lg-2 sub-comment" style="padding-top:10px;text-align:center;">
      <span>
        <% if comment.ticket_owner == "CyberAdvance" %>
          <%= image_tag('logo.png', width: '16', height: '24') %>&nbsp;&nbsp;<font style="font-size:14px;">CyberAdvance</font>
        <% else %>
          <i class="fa fa-user"></i>&nbsp;&nbsp;<%= comment.ticket_owner.split("@").first %>
        <% end %>
      </span>
    </div>
    <div class="col-lg-9 sub-comment" style="background-color:rgba(0, 67, 116, 0.37);padding:10px 16px;"><!-- #004374 -->
      <div class="triangle">
      </div>
      <%= comment.comment%><br/><br/>
      [Update <%= comments_by_ticketid(ticket.id)-up_ind %>]
      <% up_ind = up_ind + 1 %>
      <br/>
    </div>
    <div class="col-lg-1 sub-comment" style="padding-left:0px;padding-right:0px;text-align:right">
      <%= time_ago_in_words(comment.updated_at) %> ago
    </div>
  <% end %>
<% end %>

app/views/tickets/_comment.html.erb
<%= form_tag('/tickets', method: :get) do -%>
  <div class="col-md-8">
    <%= %>
  </div>
  <div class="col-md-2" style="text-align:right">
    <%= submit_tag 'Reply', :class=>'btn btn-primary' %>
  </div>
<% end -%>

app/views/tickets/_filter.html.erb
<%#= form_tag('/tickets/filter', :style=>"margin-top:25px;", :class=>'col-md-12') do -%>
<%= simple_form_for :search, :method=>'get', :html=>{:style=>'margin-top:25px', :class=>'col-md-12'}, :remote=>true do |f| %>
  <div class="col-md-6">
    <div class="field">
      <i class="fa fa-fw fa-users" style="color:#5bc0de;font-size:18px;margin:-2px 0;position:relative;top:9px;left:8px;"></i>
      <%= text_field_tag 'group', nil, class: 'form-control', placeholder: 'Group', :style=>'margin-top:-18px;padding-left:40px;', :value=>!@filter_params.blank? ? @filter_params[:group] : nil %>
    </div>
    <div class="field">
      <i class="fa fa-fw fa-paperclip" style="color:#5bc0de;font-size:18px;margin:-2px 0;position:relative;top:9px;left:8px;"></i>
      <%= text_field_tag 'subject', nil, class: 'form-control', placeholder: 'Subject / Title', :style=>'margin-top:-18px;padding-left:40px;' , :value=>!@filter_params.blank? ? @filter_params[:subject] : nil %>
    </div>
    <div class="field">
      <i class="fa fa-fw fa-user" style="color:#5bc0de;font-size:18px;margin:-2px 0;position:relative;top:9px;left:8px;"></i>
      <%= text_field_tag 'owner', nil, class: 'form-control', placeholder: 'Owner', :style=>'margin-top:-18px;padding-left:40px;', :value=>!@filter_params.blank? ? @filter_params[:owner] : nil %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="field">
      <i class="fa fa-fw fa-reply" style="color:#5bc0de;font-size:18px;margin:-2px 0;position:relative;top:9px;left:8px;"></i>
      <%= text_field_tag 'last_replied', nil, class: 'form-control', placeholder: 'Last replied', :style=>'margin-top:-18px;padding-left:40px;', :value=>!@filter_params.blank? ? @filter_params[:last_replied] : nil %>
    </div>
    <div class="field">
      <i class="fa fa-fw fa-cog" style="color:#5bc0de;font-size:18px;margin:-2px 0;position:relative;top:9px;left:8px;"></i>
      <%= text_field_tag 'device', nil, class: 'form-control', placeholder: 'Device', :style=>'margin-top:-18px;padding-left:40px;', :value=>!@filter_params.blank? ? @filter_params[:device] : nil %>
    </div>
    <div class="field">
      <i class="fa fa-fw fa-calendar" style="color:#5bc0de;font-size:18px;margin:-2px 0;position:relative;top:9px;left:8px;"></i>
      <%= text_field_tag 'updated', nil, class: 'form-control', placeholder: 'Updated', :style=>'margin-top:-18px;padding-left:40px;', :value=>!@filter_params.blank? ? @filter_params[:updated] : nil %>
    </div>
    <div style="text-align:right;margin-right:25px;margin-bottom:25px;">
      <%= button_tag(type: "submit", :class=>'btn btn-primary btn-device') do %>
        <i class="glyphicon glyphicon-filter" style="position:relative;top:2px;"></i>&nbsp;&nbsp;Filter
      <% end %>
      <%= button_tag(:class=>'btn btn-primary btn-device', :id=>'btn_cancel_ticket_filter') do %>
        <i class="glyphicon glyphicon-remove-sign" style="position:relative;top:2px;"></i>&nbsp;&nbsp;Close
      <% end %>
    </div>
  </div>
<% end -%>

app/views/tickets/_form.html.erb
<div class="container">
  <div class="content-div" style="margin-bottom:9%">
    <%= form_for(@ticket) do |f| %>
      <% if @ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
          <% @ticket.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-md-6" style="margin:15px 0;">
        <label><span style="color:red">*</span>&nbsp;Subject:</label><br/>
        <%#= f.select :subject, options_for_select([ "Subject1", "Subject2", "Subject3", "Subject4" ], "Subject1"), :style=>'width:100%;font-size:72px;' %>
        <div class="dropdown dropdown-dark">
          <select name="two" class="dropdown-select" id="select_ticket_subject">
            <option value="">Select</option>

            <option value="API Question">API Question</option>
            <option value="Accounting Request">Accounting Request</option> 
            <option value="CDNLayer Question">CDNLayer Question</option>
            <option value="Colocation Service Request">Colocation Service Request</option>
            <option value="DNS Request">DNS Request</option>
            <option value="DOS/Abuse Issue">DOS/Abuse Issue</option>
            <option value="Hardware Firewall Question">Hardware Firewall Question</option>
            <option value="Hardware Issue">Hardware Issue</option>
            <option value="Hardware Load Balancer Question">Hardware Load Balancer Question</option>
            <option value="Licensing Question">Licensing Question</option>
            <option value="Mail Server Issue">Mail Server Issue</option>
            <option value="OS Reload Question">OS Reload Question</option>
            <option value="Portal Information Question">Portal Information Question</option>
            <option value="Private Network Question">Private Network Question</option>
            <option value="Public Network Question">Public Network Question</option>
            <option value="Reboots and Console Access">Reboots and Console Access</option>
            <option value="Sales Request">Sales Request</option>
            <option value="Security Issue">Security Issue</option>
            <option value="Storage Question">Storage Question</option>
            <option value="Transcoding Question">Transcoding Question</option>
            <option value="Vyatta Question">Vyatta Question</option>
            <option value="Other: Administrative">Other: Administrative</option>

          </select>
        </div>
        <%= f.hidden_field :subject,:required => true %>
      </div>

      <div class="col-md-6" style="margin:15px 0;">
        <label><span style="color:red">*</span>&nbsp;Assign To:</label><br/>
        <%#= f.select :owner, options_for_select(@emails),:style=>'width:100%;font-size:72px;' %>
        <div class="dropdown dropdown-dark">
          <select name="two" class="dropdown-select" id="select_ticket_owner">
            <option value="">Select</option>
            <%# @emails.each do |e| %>
              <!-- <option value="<%#= e%>"><%#= e%></option> -->
            <%# end %>
            <option value="<%= @emails %>"><%= @emails %></option>
          </select>
        </div>
        <%= f.hidden_field :owner, :required => true%>
      </div>

      <div class="col-md-12" style="margin: 15px 0;">
        <label><span style="color:red">*</span>&nbsp;Title:</label><br/>
        <%= f.text_field :ticket_group, :class=>'form-control',:required => true %>
      </div>

      <div class="col-md-12" style="margin: 15px 0;">
        <label><span style="color:red">*</span>&nbsp;Email Address:</label><br/>
        <div class="dropdown dropdown-dark">
          <select name="two" class="dropdown-select" id="select_ticket_last_replied">
            <option value="">Select</option>
            <option value="<%=current_user.email%>"><%= current_user.email%></option>            
          </select>
        </div>
        <%= f.hidden_field :last_replied, :required => true, :value=>nil%>
        <%#= f.hidden_field :owner, :required => true %>
      </div>

      <div class="col-md-12" style="margin: 15px 0;">
        <label><span style="color:red">*</span>&nbsp;Device:</label><br/>
        <div class="dropdown dropdown-dark" id="">
          <select name="two" class="dropdown-select"  id="select_ticket_device">
            <option value="">Select</option>
            <%# @devices.each do |d| %>
              <!-- <option value="<%#=d.name%>"><%#= d.name%></option> -->
            <%# end %>
            <% get_devices(current_user.username).each do |d| %>
              <option value="<%=d.name%>"><%= d.name%></option>
            <% end %>
          </select>
        </div>
        <%= f.hidden_field :device, :required => true %>
        <%#= f.text_field :device, :class=>'form-control' %>
      </div>

      <div class="col-md-12" style="margin: 15px 0;">
        <label><span style="color:red">*</span>&nbsp;Detail:</label><br/>
        <%= f.text_area :detail, :class=>"form-control", :rows=>'6', :required => true%>
        <%#= f.text_field :updated, :class=>'form-control', :value=>Time.now, :readonly => true %>
      </div>
      <%= f.hidden_field :is_read, :value=>true %>
      <%= f.hidden_field :updated, :value=>Time.now %>
      <div class="action" style="text-align:right;margin-right:25px">
        <%= button_tag(type: "submit", :class=>'btn btn-primary btn-device') do %>
          <i class="glyphicon glyphicon-tags"></i>&nbsp;&nbsp;Add Ticket
        <% end %>
        <%= link_to(tickets_path, :class=>'btn btn-primary btn-device') do %>
          <i class="glyphicon glyphicon-hand-left"></i>&nbsp;&nbsp;Back
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tickets/edit.html.erb
<div class="content-div">
  <h1>Editing Ticket</h1>

  <%= render 'form' %>

  <%#= link_to 'Show', @ticket %> 
  <%#= link_to 'Back', tickets_path %>
</div>

app/views/tickets/index.html.erb
<!-- <div class="container" style="min-width:1053px;"> -->
<div class="container">
  <!-- <div class="div-notice" style="min-width:1024px;"> -->
  <div class="div-notice">
    <%= notice %>
    <% if @note_count.to_i == 0 && @dnote_count.to_i == 0 %>
      <%= "You have no new notification." %>
    <% else %>
      <%= "You have unread notifications for events which may affect your services" %>
    <% end %>
    <ul class="nav navbar-nav navbar-right note-ul" style="margin-right:0px;">
      <li>
        <% if @dnote_count.to_i != 0 || @note_count.to_i != 0 %>
          <% if @dnote_count.to_i != 0 %>
            <span class="span-note" note="devices" style="text-decoration:underline;cursor:pointer;">
          <% else %>
            <span class="span-note" note="tickets" style="text-decoration:underline;cursor:pointer;">
          <% end %>
            <%= @note_count.to_i + @dnote_count.to_i %> Notifications
          </span>
        <% end %>
      </li>
      <li><span class="span-close" style="cursor:pointer;"><i class="glyphicon glyphicon-remove"></i></span></li>
    </ul>
  </div>

  <!-- <div class="content-div" style="margin-bottom:9%;min-width:1024px;"> -->
  <div class="content-div" style="margin-bottom:9%;">
    <h1>
      <% if hp_ticket(current_user.username) %>
        <%= link_to(new_ticket_path, :class=>'link-plus', :style=>'margin-top:-8px;text-decoration:none;') do %>
          &nbsp;<i class="glyphicon glyphicon-tags" style="font-size:24px;color:yellow;"></i>
          <i class="glyphicon glyphicon-plus" style="font-size:10px;margin-left:-8px;"></i>
        <% end %>
      <% end %>
      Tickets
    </h1>
    <!-- <div style="padding: 10px 0;min-width:930px;"> -->
    <div id="tickets">
      <%= render 'tickets/tickets' %>
    </div>
    <br>
  </div>
</div>

app/views/tickets/index.js.erb
<% if !params[:content].nil? %>
  <% ct = Ticket.find_by_id(params[:ticket_id]) %>

  jQuery('textarea[data-id=<%=params[:ticket_id]%>]').val('');
  jQuery('textarea[data-id=<%=params[:ticket_id]%>]').focus();
  jQuery('#add_comment_<%=params[:ticket_id]%>').html("<%= j(render :partial=>'add_comment', :locals=>{:ticket=>ct}) %>");
<% else %>
  jQuery('#tickets').html("<%= j(render 'tickets/tickets') %>");
<% end %>

$('.pagination a').attr('data-remote', 'true');
$('#select_ticket_rows').attr('data-remote', 'true');

app/views/tickets/new.html.erb
<h1 style="text-align:center;color:white">New Ticket</h1>

<div class="container">
  <div class="div-notice">
    <i class="glyphicon glyphicon-exclamation-sign" style="color:yellow"></i>&nbsp;Attention : All fields are required one.
    <% if @note_count == 0 %>
      <%= "You have no new notification." %>
    <% else %>
      <%= "You have unread notifications for events which may affect your services" %>
    <% end %>
    <ul class="nav navbar-nav navbar-right note-ul" style="margin-right:0px;">
      <% if @note_count != 0 %>
        <li><span class="span-note" style="text-decoration:underline;cursor:pointer;"><%= @note_count%> Notifications</span></li>
      <% end %>
      <li><span class="span-close" style="cursor:pointer;"><i class="glyphicon glyphicon-remove"></i></span></li>
    </ul>
  </div>
</div>

<%= render 'form' %>

<%#= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<div class="container">
  <div class="div-notice">
    <%= notice %>
    <% if @note_count == 0 %>
      <%= "You have no new notification." %>
    <% else %>
      <%= "You have unread notifications for events which may affect your services" %>
    <% end %>
    <ul class="nav navbar-nav navbar-right note-ul" style="margin-right:0px;">
      <% if @note_count != 0 %>
        <li><span class="span-note" style="text-decoration:underline;cursor:pointer;"><%= @note_count%> Notifications</span></li>
      <% end %>
      <li><span class="span-close" style="cursor:pointer;"><i class="glyphicon glyphicon-remove"></i></span></li>
    </ul>
  </div>
</div>

<div class="border-form-div">
  <!-- <p id="notice"><%= notice %></p>
   -->
  <p>
    <strong>Group:</strong>
    <%= @ticket.ticket_group %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= @ticket.subject %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= @ticket.owner %>
  </p>

  <p>
    <strong>Last replied:</strong>
    <%= @ticket.last_replied %>
  </p>

  <p>
    <strong>Device:</strong>
    <%= @ticket.device %>
  </p>

  <p>
    <strong>Updated:</strong>
    <%= @ticket.updated %>
  </p>

  <%= link_to 'Edit', edit_ticket_path(@ticket), :class=>'btn btn-primary' %>
  <%= link_to 'Back', tickets_path, :class=>'btn btn-primary' %>
</div>